### PR TITLE
fixed #167 depraciation warnings

### LINKED ISSUE #167: Depreciation warnings on the command prompt
bug1

### PR DESCRIPTION
**Pull request by Creatoon**
# What's this PR do? (related issue if exists)
Previously I solved this issue but accidentally changed the indentation of the codebase, this PR includes a fix of Depreciation warnings appearing in the console, further details in the screenshot below.

issue is solved.

bugFix

### CODE REVIEW

**Comment by Creatoon** [comment]
this pr resolved issue #167

**Comment by dheeraj135** [comment]
Changes looks ok to me. @Signior-X will review and merge this PR.

**Comment by Signior-X** [comment]
@pranshukharkwal do we need to remove the depreciation warning.... what say?
Changes seem good to me.

**Comment by pranshukharkwal** [comment]
@Signior-X Yes I think it is good to get rid to such warnings. You can merge the PR if the code changes are correct.

**Comment by Signior-X** [comment]
Yes the code is exact to the point @pranshukharkwal merging it.
Great work done @Creatoon 

Hope to see more contribution from your side.

**Pull request merged**
