### PR TITLE
Bug: Problem id pointing to the particular problem

### LINKED ISSUE #156: [BUG] Link to problem in an individual problem submission page points to a wrong url
Screenshot from 2020-12-09 19-47-21
http://localhost:3000/user/submission/28
Check this route : /user/submission/:submissionId , example : /user/submission/5
Here in the problem column, the link points to the submission with submission id, but instead it should point to the problem with that problem id.

### PR DESCRIPTION
**Pull request by Gautam-Arora24**
**Fixes #156**

**Changes Proposed**
The problem id in the table should point to the particular problem.

**My Solution**
Now on clicking the id number, the page redirects to the particular problem. Though the link I used is localhost, it should be changed once the application is in production.

### CODE REVIEW

**Comment by pranshukharkwal** [comment]
Hi @Gautam-Arora24 
Do not use http://localhost:3000 in the code because it will cause problems later on when we host this site on other domains. Make it domain independent.

**Comment by Gautam-Arora24** [comment]
That's what I told that this need to be changed when the application is on production. Still I am looking a better way for it

**Comment by pranshukharkwal** [comment]
@Gautam-Arora24 I think only including /problem/qId will solve the problem i.e removing the localhost:3000 part. See if it works. If  not, we will look for some other solution.

**Comment by Gautam-Arora24** [comment]
Sure Lemme check

**Pull request closed without merging**
