### PR TITLE
Time and Memory Limit Issue Resolved

### PR DESCRIPTION
**Pull request by shrirangpdeshmukh**
# What's this PR do? (related issue if exists)
Resolving issue [#141 ](https://github.com/KamandPrompt/CodeManiacs/issues/141)
Made memory limit and time limit necessary fields and assigned them default values.
# Any context you want to provide on the implementation?

# Screenshots? (necessary if an UI/UX change)
Capture

### CODE REVIEW

**Comment by Signior-X** [comment]
Awesome work done @shrirangpdeshmukh 
Good to merge this PR.

However remember while making PRs or working on some feature, try to **work on a different branch** than the main(master) branch. As while in master, if you need to update the PR, it can be a problem.

**Review by Signior-X — APPROVED** [review]

**Comment by shrirangpdeshmukh** [comment]
@Siginor-X thank you for the suggestion. I will keep that in mind.

**Comment by Signior-X** [comment]
@shrirangpdeshmukh one thing I forgot, the changes are working good.
Make the same changes in problem edit page and files.
Then we will be ready to merge.

**Review by Signior-X — CHANGES_REQUESTED** [review]
Make the similar changes in problem_edit.ejs and problem_edit.js files.

**Comment by shrirangpdeshmukh** [comment]
I made a similar change to the .ejs as well as .js file in problem_edit.
check function was not present in the problem.js. I have added it to ensure the similar checks happen during problem edit.

**Comment by pranshukharkwal** [comment]
@shrirangpdeshmukh  could you also add the units of time(seconds) and memory(kb) in the problem add page. They are added in the problem edit page but not in problem add page. 
So we could have that as well in the same PR.

**Comment by shrirangpdeshmukh** [comment]
Added units to Problem_Add.ejs
Screenshot (736)
Changed Textarea to input type =number and added validation to it for minimum value=1

**Comment by Signior-X** [comment]
Cool nice work @shrirangpdeshmukh 
@pranshukharkwal you also check this and merge this.

**Comment by pranshukharkwal** [comment]
Screenshot from 2020-12-09 19-12-15
@shrirangpdeshmukh I am still able to create a problem with memory limit and time limit = 0. Like if you use the arrows, then it won't go below 1, but if you type manually, then you can enter any value, even negative.
Could you please check why this is happening and how to fix it.

**Comment by shrirangpdeshmukh** [comment]
Okay I will look into this

**Comment by shrirangpdeshmukh** [comment]
Added a JS Validation the Time and Memory Limits
Screenshot (739)
An alert is sent for this.
Screenshot (740)

**Comment by pranshukharkwal** [comment]
Good work @shrirangpdeshmukh 
Works good now, thanks :+1:

**Pull request merged**
