### PR TITLE
Fixed #169 disappearing of images

### LINKED ISSUE #169: Disappearing of images after 1.5seconds.
Whenever a new image gets loaded it stays for 1.5s and gets disappeared.

To Reproduce,
1) Visit the About section.
2) Click the forward and backward buttons to see the disappearing defect.

CodemanBugFix

After few seconds.

codemanBug

### PR DESCRIPTION
**Pull request by Creatoon**
# What's this PR do? (related issue if exists)
This will fix the issue discussed in #169 

# Screenshots? (necessary if a UI/UX change)
Screenshots of images are available there at issue #169

### CODE REVIEW

**Comment by pranshukharkwal** [comment]
Hi @Creatoon Good work on this ! 
Also these images are not center aligned as in this screenshot. Can you fix this too in this PR? 
Screenshot from 2020-12-15 01-43-11
Also the buttons for switching the images appear in the top right corner, which doesn't look good. This could be added in the center I guess. What do you think?

**Comment by Creatoon** [comment]
@pranshukharkwal Working on this.

**Comment by Creatoon** [comment]
1) Slideshow container is centred aligned now.
2) Dots are in the bottom of the slideshow container

solvedSlideshow

**Comment by pranshukharkwal** [comment]
@Creatoon The expected behaviour for the images in the slides with to change automatically to the other after 1.5 seconds. 
From what you have done, they do not change at all. So while the bug of images disappearing has been fixed, the expected behaviour is still not attained. 
Could you please look into this?

Also have you made any indentation changes in the existing code?

**Comment by Creatoon** [comment]
@pranshukharkwal I am looking at the issue, no I haven't  made any indentation changes.

**Comment by Creatoon** [comment]
@pranshukharkwal  slideshow is working now, but buttons are not doing well, please check it, otherwise, it is also looking good as compared to previous.

**Comment by pranshukharkwal** [comment]
@Creatoon Can you make the buttons work?

**Comment by Creatoon** [comment]
@pranshukharkwal this task can be simply done with a small library ~ Owl Carousel.
Both slideshow and button will work. 
If you allow me I can do this. 
Otherwise it will be more tricky by doing it manually.

**Comment by pranshukharkwal** [comment]
@Creatoon yes you can totally use owl carousel.

**Comment by Creatoon** [comment]
@pranshukharkwal Working on it. 
Also please review another pr's

**Comment by pranshukharkwal** [comment]
@Creatoon @Signior-X will review #168

**Comment by Creatoon** [comment]
@pranshukharkwal  Slideshow is working now , both automatically and with buttons.

https://user-images.githubusercontent.com/65965202/102716808-2daa5580-4304-11eb-80e5-bce7348d855e.mp4

**Comment by Creatoon** [comment]
@pranshukharkwal please review this pr , from my side it is working fine , if you need some changes just let me know.

**Comment by pranshukharkwal** [comment]
@Creatoon Yes looks good. One final change, I think the speed of the carousel is very high. Please reduce it a little, like change in 1 second maybe.

**Comment by Creatoon** [comment]
@pranshukharkwal is it ok now, the speed?

**Comment by Signior-X** [comment]
@Creatoon cool, I think now it is fine.
Also the format is nice. Will merge this soon!

**Pull request merged**
