### PR TITLE
Resolved depreciation warnings in the console

### PR DESCRIPTION
**Pull request by Creatoon**
# What's this PR do? (related issue if exists)
this PR includes the fix of depraciation warning , more on the screenshot.

# Any context you want to provide on the implementation?

# Screenshots? (necessary if an UI/UX change)
bug1

after fixing

bugFix

### CODE REVIEW

**Comment by pranshukharkwal** [comment]
Good work on this @Creatoon 
Is this PR based on some issue or did you come up with the issue by yourself? 
If the latter is the case, then I would suggest you to first create issues, and then discuss with us and the community, and then start working on them.

**Comment by vsvipul** [comment]
Hello @Creatoon , you are also changing indentation of code which isn't required. Remove those changes and only keep the changes which are necessary for fixing the depreciation warning as mentioned on your PR. If you want to fix alignment, you can do that in a separate PR.

**Comment by Creatoon** [comment]
@pranshukharkwal Ok sir, i will keep it in mind from this time, now do i have to raise an issue to create the same pull request.

**Comment by Creatoon** [comment]
@vsvipul  Ok sir, I am deleting this pr, and raise a new issue with the same fix without indentation.

**Comment by Creatoon** [comment]
fixed #161

**Comment by dheeraj135** [comment]
Hey @Creatoon, Please don't change the existing indentation of the codebase. It would be better to do that as a separate issue. Every PR should solve just one issue, here, it should be to remove the deprecation warnings. Please remove the changes and squash the changes.

**Pull request closed without merging**
