### PR TITLE
Added an installation video

### PR DESCRIPTION
**Pull request by Creatoon**
# What's this PR do? (related issue if exists)
This PR solves issue #172 

# Any context you want to provide on the implementation?
You can change the speed of the video from the URL "SPEED" option.

### CODE REVIEW

**Comment by Signior-X** [comment]
I think the video is fine.
@pranshukharkwal can you also suggest if this is good, so we can merge this one.

**Comment by pranshukharkwal** [comment]
@Creatoon @Signior-X 
I think the mongodb setup part, and getting admin privileges part should also be added to the video. Like a basic walk through of the project. 
Also @Creatoon, is voiceover possible from your end? Maybe then the video will be more explanatory and helpful.

**Comment by Creatoon** [comment]
@pranshukharkwal yes this is possible, but then the video will be on youtube, I am working on this

**Comment by pranshukharkwal** [comment]
@Creatoon Yes sure, we can keep the video file in the repository and also add youtube link in the readme file.

**Comment by Signior-X** [comment]
@Creatoon are you still working on this?

**Comment by Creatoon** [comment]
@Signior-X No sir, I have a problem with my video editing software that's why I haven't done that.

**Pull request closed without merging**
